-- noinspection SqlNoDataSourceInspectionForFile

CREATE SEQUENCE SQ_VEICULO
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE TB_VEICULO (
    ID BIGINT PRIMARY KEY DEFAULT nextval('SQ_VEICULO'),
    NM_VEICULO VARCHAR(255) NOT NULL,
    NM_MARCA VARCHAR(255) NOT NULL,
    ANO INTEGER NOT NULL,
    DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION atualiza_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.DT_ATUALIZACAO = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_atualiza_timestamp
    BEFORE UPDATE ON TB_VEICULO
    FOR EACH ROW
    EXECUTE FUNCTION atualiza_timestamp();

CREATE SEQUENCE SQ_REVISAO
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE TB_REVISAO (
    ID BIGINT PRIMARY KEY DEFAULT nextval('SQ_REVISAO'),
    NM_VEICULO VARCHAR(255) NOT NULL,
    NM_MARCA VARCHAR(255) NOT NULL,
    DS_PROBLEMA VARCHAR(500),
    FL_ATIVO BOOLEAN DEFAULT TRUE
);

INSERT INTO TB_VEICULO (NM_VEICULO, NM_MARCA, ANO) VALUES ('Fusca', 'Volkswagen', 2020);
INSERT INTO TB_VEICULO (NM_VEICULO, NM_MARCA, ANO) VALUES ('Civic', 'Honda', 2021);

INSERT INTO TB_REVISAO (NM_VEICULO, NM_MARCA, DS_PROBLEMA, FL_ATIVO) VALUES ('Fusca', 'Volkswagen', 'Troca de óleo', TRUE);
INSERT INTO TB_REVISAO (NM_VEICULO, NM_MARCA, DS_PROBLEMA, FL_ATIVO) VALUES ('Civic', 'Honda', 'Revisão geral', TRUE);