spring.application.name=oficina

spring.datasource.url=jdbc:postgresql://localhost:5432/oficina
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

log.level=INFO
logging.level.root=${log.level}
logging.level.springframework=${log.level}
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=${log.level}
logging.level.org.springframework.web.client.RestTemplate=${log.level}